# Generated by Django 4.0.3 on 2022-03-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_address'),
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='society_type',
        ),
        migrations.AddField(
            model_name='member',
            name='doc_id',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='doc_type',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='secretary',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
