# Generated by Django 4.0.3 on 2022-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_remove_member_society_type_member_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='residence_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Tenant', 'Tenant')], max_length=20),
        ),
    ]
