# Generated by Django 4.0.3 on 2022-03-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_address'),
        ('clientapp', '0003_alter_member_residence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
