# Generated by Django 4.0.3 on 2022-04-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_alter_member_secretary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=20)),
                ('ad_price', models.CharField(max_length=20)),
                ('ad_des', models.TextField()),
                ('ad_image1', models.FileField(blank=True, upload_to='Ads/')),
                ('ad_image2', models.FileField(blank=True, upload_to='Ads/')),
                ('ad_image3', models.FileField(blank=True, upload_to='Ads/')),
                ('ad_image4', models.FileField(blank=True, upload_to='Ads/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.member')),
            ],
        ),
    ]
