# Generated by Django 4.0.3 on 2022-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_image1',
            field=models.FileField(blank=True, upload_to='Ads'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_image2',
            field=models.FileField(blank=True, upload_to='Ads'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_image3',
            field=models.FileField(blank=True, upload_to='Ads'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ad_image4',
            field=models.FileField(blank=True, upload_to='Ads'),
        ),
    ]
