# Generated by Django 4.0.3 on 2022-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_complaint_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
